// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://go-news.example.com/terms/",
        "contact": {
            "name": "Вымышленная команда поддержки GoNews",
            "url": "https://go-news.example.com/support",
            "email": "support@go-news.example.com"
        },
        "license": {
            "name": "MIT License",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/comments": {
            "post": {
                "description": "Создать новый комментарий для конкретной новости.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comments"
                ],
                "summary": "Создать новый комментарий",
                "parameters": [
                    {
                        "description": "Данные нового комментария",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CommentResponse"
                        }
                    }
                }
            }
        },
        "/api/news": {
            "get": {
                "description": "Возвращает список всех новостей.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "news"
                ],
                "summary": "Получить все новости",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Страница",
                        "name": "page",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "default": "\"\"",
                        "description": "Поиск заголовка",
                        "name": "search",
                        "in": "path"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Страница",
                        "name": "limit",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.Post"
                            }
                        }
                    }
                }
            }
        },
        "/api/news/last": {
            "get": {
                "description": "Возвращает последнюю новость.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "news"
                ],
                "summary": "Получить последнюю новость",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Post"
                        }
                    }
                }
            }
        },
        "/api/news/latest/{limit}": {
            "get": {
                "description": "Возвращает последние n новостей.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "news"
                ],
                "summary": "Получить последние n новостей",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Количество последних новостей",
                        "name": "limit",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Post"
                        }
                    }
                }
            }
        },
        "/api/news/{id}": {
            "get": {
                "description": "Возвращает новость по ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "news"
                ],
                "summary": "Получить новость по ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID новости",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.PostWithComments"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Возвращает статус сервиса, аптайм и версию.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/health.HealthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.Comment": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Comment"
                    }
                },
                "content": {
                    "type": "string",
                    "example": "Example content"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "news_id": {
                    "type": "integer",
                    "example": 1
                },
                "parent_id": {
                    "type": "integer",
                    "example": 1
                },
                "pub_time": {
                    "type": "string",
                    "example": "2025-06-26 10:00:43"
                },
                "username": {
                    "type": "string",
                    "example": "Example_username"
                }
            }
        },
        "dto.CommentResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Example message success"
                },
                "status": {
                    "type": "string",
                    "example": "OK"
                }
            }
        },
        "dto.CreateCommentRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "example": "Example content"
                },
                "news_id": {
                    "type": "integer",
                    "example": 1
                },
                "parent_id": {
                    "type": "integer",
                    "example": 1
                },
                "username": {
                    "type": "string",
                    "example": "Example_username"
                }
            }
        },
        "dto.Post": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "link": {
                    "type": "string"
                },
                "pub_time": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dto.PostWithComments": {
            "type": "object",
            "properties": {
                "comments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Comment"
                    }
                },
                "post": {
                    "$ref": "#/definitions/dto.Post"
                }
            }
        },
        "health.HealthResponse": {
            "type": "object",
            "properties": {
                "service": {
                    "type": "string",
                    "example": "api-gateway"
                },
                "status": {
                    "type": "string",
                    "example": "OK"
                },
                "uptime": {
                    "type": "string",
                    "example": "1h23m45s"
                },
                "version": {
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "GoNews API Gateway",
	Description:      "API-шлюз для микросервисов агрегатора новостей и комментариев.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
