app:
  name: ${APP_NAME}
  read_timeout: 10
  write_timeout: 10
  enable_request_id: true
  enable_logging: true
  enable_error_handling: true

http:
  host: ${HTTP_HOST}
  port: ${HTTP_PORT}

logging:
  level: ${LOGGING_LEVEL}
  format: ${LOGGING_FORMAT}
  enable_http_logs: ${LOGGING_ENABLE_HTTP}